AllCops:
  Exclude:
    - "*.gemspec"
    - Rakefile

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

Metrics:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

